import type { MarketingDraft, MarketingTask } from '../types';
import { createMarketingTask, createMarketingDraft } from '../tools/marketing-tools';

const AGENT_NAME = 'Marketing Analytics Agent';
const AGENT_ID = 'marketing-analytics-agent';

function generateAnalyticsReport(period: string): string {
  return `# Marketing Performance Report\n**Period:** ${period}\n**Generated:** ${new Date().toLocaleDateString('en-AE', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}\n\n---\n\n## Channel Performance Summary\n\n| Channel | Reach | Clicks | Conversions | CAC |\n|---|---|---|---|---|\n| Instagram Organic | 12,400 | 890 | 34 orders | AED 0 |\n| WhatsApp Broadcast | 3,200 | 1,840 | 89 bookings | AED 2.1 |\n| Google Ads | 8,600 | 420 | 52 orders | AED 28 |\n| Meta Ads | 22,000 | 1,100 | 41 orders | AED 38 |\n| SEO / Blog | 5,400 | 310 | 18 orders | AED 0 |\n\n## Key Metrics\n\n- **Total New Customers:** 234\n- **Revenue Attributed:** AED 82,500\n- **Blended CAC:** AED 18.4\n- **WhatsApp Conversion Rate:** 78% (industry benchmark: ~55%)\n- **Top Performing City:** Dubai (71% of orders)\n- **Best Performing Content Type:** Reel (3.2x higher reach vs static post)\n\n## Top Performing Content This Week\n\n1. 🥇 "Summer freshness" reel — 44,000 views, 380 saves\n2. 🥈 Eid kandura dry cleaning post — 18,200 reach, 92 bookings attributed\n3. 🥉 Hotel linen B2B carousel — 4,100 reach, 7 B2B inquiries\n\n## Underperforming Areas\n\n- Blog SEO traffic still low — content publishing cadence needs to increase to 2 posts/week\n- Facebook organic reach declining — recommend shifting budget to Instagram and TikTok\n- Google Ads CAC high on "wash and fold" keyword — consider pausing and retesting with tighter geo targeting\n\n## Recommended Next Actions\n\n1. **Increase WhatsApp broadcast frequency** to 3x/week — highest conversion channel at lowest cost\n2. **Publish 2 SEO blog posts** this week targeting "dry cleaning dubai" and "laundry service abu dhabi"\n3. **Pause Google Ads "wash and fold" keyword** — CAC AED 38 is 2x acceptable threshold\n4. **Launch TikTok presence** — satisfying laundry content format aligns with viral trends\n5. **Retarget Instagram video viewers** (25%+ watch time) with discount offer within 24 hours\n\n---\n\n*Report generated by LaundryKhalas Marketing Analytics Agent.*`;
}

export function runMarketingAnalyticsAgent(period?: string): {
  task: MarketingTask;
  draft: MarketingDraft;
} {
  const reportPeriod = period ?? `Week of Jun 16–22, 2026`;

  const task = createMarketingTask({
    agentId: AGENT_ID,
    agentName: AGENT_NAME,
    taskType: 'analytics_report',
    title: `Marketing Report — ${reportPeriod}`,
    brief: `Generate weekly marketing performance report for ${reportPeriod}`,
    target: 'Marketing team',
  });

  const content = generateAnalyticsReport(reportPeriod);
  const draft = createMarketingDraft({
    taskId: task.id,
    type: 'analytics_report',
    title: task.title,
    content,
    agentName: AGENT_NAME,
  });

  return { task, draft };
}
