import type { AgentRegistration } from './types';

export const AGENT_REGISTRY: AgentRegistration[] = [
  // ── Operations Agents ──────────────────────────────────────────
  {
    id: 'customer-order-agent',
    name: 'Customer Order Agent',
    description: 'Handles inbound WhatsApp conversations — collects order details, creates drafts, confirms bookings, answers FAQs.',
    category: 'operations',
    status: 'active',
    lastRun: '2 min ago',
    runsToday: 47,
    successRate: 91,
    avgDurationMs: 320,
    isEnabled: true,
    color: 'text-pink-600 bg-pink-50',
    capabilities: [
      'Collect name, phone, address, service type, pickup slot',
      'Create and confirm order drafts',
      'Answer service and pricing FAQs',
      'Check order status on request',
    ],
  },
  {
    id: 'intent-classifier',
    name: 'Intent Classifier',
    description: 'Classifies every inbound message into a structured intent type and routes it to the correct agent workflow.',
    category: 'operations',
    status: 'active',
    lastRun: '1 min ago',
    runsToday: 89,
    successRate: 97,
    avgDurationMs: 45,
    isEnabled: true,
    color: 'text-blue-600 bg-blue-50',
    capabilities: [
      'Classify 12 intent types',
      'Detect sentiment signals',
      'Route to correct agent',
      'Flag ambiguous messages for review',
    ],
  },
  {
    id: 'orchestration-agent',
    name: 'Operations Orchestrator',
    description: 'Coordinates facility assignment, driver dispatch, slot availability checks, and order status updates across operations.',
    category: 'operations',
    status: 'active',
    lastRun: '8 min ago',
    runsToday: 34,
    successRate: 94,
    avgDurationMs: 210,
    isEnabled: true,
    color: 'text-purple-600 bg-purple-50',
    capabilities: [
      'Check facility capacity and availability',
      'Find and assign nearest available driver',
      'Update order status through pipeline',
      'Notify operations team of critical events',
    ],
  },
  {
    id: 'escalation-agent',
    name: 'Human Escalation Agent',
    description: 'Detects when a human must take over — creates escalation records, summarizes context, and recommends next actions.',
    category: 'operations',
    status: 'active',
    lastRun: '22 min ago',
    runsToday: 8,
    successRate: 100,
    avgDurationMs: 160,
    isEnabled: true,
    color: 'text-red-600 bg-red-50',
    capabilities: [
      'Detect complaint, refund, and high-risk intents',
      'Create structured escalation records',
      'Summarize conversation for human agent',
      'Recommend immediate next action',
    ],
  },
  // ── Marketing Agents ───────────────────────────────────────────
  {
    id: 'content-planning-agent',
    name: 'Content Planning Agent',
    description: 'Generates weekly and monthly content calendars with campaign themes, seasonal hooks, and platform-specific scheduling.',
    category: 'marketing',
    status: 'idle',
    lastRun: '2 hrs ago',
    runsToday: 3,
    successRate: 100,
    avgDurationMs: 890,
    isEnabled: true,
    color: 'text-emerald-600 bg-emerald-50',
    capabilities: [
      'Weekly content calendar generation',
      'Campaign theme suggestions',
      'Seasonal and UAE-specific content hooks',
      'Multi-platform scheduling (IG, FB, WA, Blog)',
    ],
  },
  {
    id: 'social-content-agent',
    name: 'Social Media Agent',
    description: 'Generates captions, post copy, reel ideas, story ideas, and carousel content for Instagram, Facebook, and TikTok.',
    category: 'marketing',
    status: 'idle',
    lastRun: '3 hrs ago',
    runsToday: 6,
    successRate: 98,
    avgDurationMs: 740,
    isEnabled: true,
    color: 'text-fuchsia-600 bg-fuchsia-50',
    capabilities: [
      'Instagram and Facebook captions',
      'Reel and story concepts',
      'Carousel post structure',
      'Hashtag strategy for UAE audience',
    ],
  },
  {
    id: 'brand-review-agent',
    name: 'Brand Review Agent',
    description: 'Reviews all marketing content for tone, grammar, pricing accuracy, brand compliance, and potential safety issues before approval.',
    category: 'marketing',
    status: 'idle',
    lastRun: '3 hrs ago',
    runsToday: 5,
    successRate: 100,
    avgDurationMs: 410,
    isEnabled: true,
    color: 'text-amber-600 bg-amber-50',
    capabilities: [
      'Brand tone and voice compliance',
      'Grammar and spelling review',
      'Pricing claim accuracy',
      'Cultural and regulatory sensitivity (UAE)',
    ],
  },
  {
    id: 'seo-agent',
    name: 'SEO & Blog Agent',
    description: 'Generates blog topics, SEO keyword clusters, city landing page briefs, and service page copy optimized for UAE search.',
    category: 'marketing',
    status: 'idle',
    lastRun: '1 day ago',
    runsToday: 1,
    successRate: 100,
    avgDurationMs: 1100,
    isEnabled: true,
    color: 'text-green-600 bg-green-50',
    capabilities: [
      'UAE local SEO keyword research',
      'Blog post outlines and briefs',
      'City-specific landing page copy',
      'On-page optimization guidance',
    ],
  },
  {
    id: 'ads-agent',
    name: 'Paid Ads Agent',
    description: 'Generates ad copy variants, audience targeting ideas, A/B test suggestions, and campaign structures for Meta and Google Ads.',
    category: 'marketing',
    status: 'idle',
    lastRun: '1 day ago',
    runsToday: 2,
    successRate: 96,
    avgDurationMs: 680,
    isEnabled: true,
    color: 'text-blue-600 bg-blue-50',
    capabilities: [
      'Meta Ads copy and creative concepts',
      'Google Ads headline and description variants',
      'A/B test copy variations',
      'Audience and interest targeting suggestions',
    ],
  },
  {
    id: 'lead-gen-agent',
    name: 'Lead Generation Agent',
    description: 'Qualifies inbound B2B leads, suggests follow-up messaging, prepares handoff notes, and tracks lead progression.',
    category: 'marketing',
    status: 'idle',
    lastRun: '4 hrs ago',
    runsToday: 4,
    successRate: 88,
    avgDurationMs: 520,
    isEnabled: true,
    color: 'text-indigo-600 bg-indigo-50',
    capabilities: [
      'B2B lead qualification framework',
      'Follow-up message suggestions',
      'Sales handoff notes',
      'Lead scoring and prioritization',
    ],
  },
  {
    id: 'marketing-analytics-agent',
    name: 'Marketing Analytics Agent',
    description: 'Generates performance summaries, weekly campaign reports, channel attribution insights, and actionable recommendations.',
    category: 'marketing',
    status: 'idle',
    lastRun: 'Yesterday',
    runsToday: 1,
    successRate: 100,
    avgDurationMs: 960,
    isEnabled: true,
    color: 'text-cyan-600 bg-cyan-50',
    capabilities: [
      'Weekly campaign performance summary',
      'Channel attribution analysis',
      'Conversion funnel insights',
      'Next-action recommendations',
    ],
  },
];

export function getAgentById(id: string): AgentRegistration | undefined {
  return AGENT_REGISTRY.find(a => a.id === id);
}

export function getAgentsByCategory(category: AgentRegistration['category']): AgentRegistration[] {
  return AGENT_REGISTRY.filter(a => a.category === category);
}
